using MicroS_Common.Messages;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.domain.<%=domain %>s.Messages.Events
{
    [MessageNamespace("<%=domain %>s")]
    public abstract class <%= pascalDomain %>BaseEvent:BaseEvent
    {
    }
}
