using MicroS_Common.Messages;
using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Messages.Events
{
    [MessageNamespace("<%= changeCase.lowerCase(name)%>s")]
    public class <%= changeCase.pascalCase(name)%>BaseRejectedEvent : BaseRejectedEvent
    {
        public <%= changeCase.pascalCase(name)%>BaseRejectedEvent(Guid id, string reason, string code) : base(id, reason, code)
        {
        }
    }
}
