using MicroS_Common.Messages;
using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.domain.<%= domain%>s.Messages.Events
{
    [MessageNamespace("<%= domain%>s")]
    public class <%= pascalDomain%>BaseRejectedEvent : BaseRejectedEvent
    {
        public <%= pascalDomain%>BaseRejectedEvent(Guid id, string reason, string code) : base(id, reason, code)
        {
        }
    }
}
