using Newtonsoft.Json;
using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.domain.<%= domain%>s.Messages.Events
{
    public class <%= pascalDomain%>Deleted:<%= pascalDomain%>BaseEvent
    {

        public Guid Id { get; }

        public <%= pascalDomain%>Deleted(Guid id)
        {
            Id = id;
        }
    }
}
