using Newtonsoft.Json;
using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Messages.Events
{
    public class <%= changeCase.pascalCase(name)%>Deleted:<%= changeCase.pascalCase(name)%>BaseEvent
    {

        public Guid Id { get; }

        public <%= changeCase.pascalCase(name)%>Deleted(Guid id)
        {
            Id = id;
        }
    }
}
