using MicroS_Common.Controllers;
using MicroS_Common.Mvc;
using MicroS_Common.RabbitMq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using OpenTracing;
using System;
using System.Threading.Tasks;
using <%=appname%>.api.Framework;
using <%=appname%>.api.Services;
using <%=appname%>.domain.<%= domain %>s.Messages.Commands;
using <%=appname%>.domain.<%= domain %>s.Queries;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.api.Controllers
{
    /// <summary>
    /// <%= pascalDomain %> Controller that represent tha main API layer
    /// on wich each request must be made
    /// </summary>
    [AdminAuth]
    [Route("<%= domain %>s")]
    public partial class <%= pascalDomain %>sController : BaseController
    {
        #region private variables
        private readonly I<%= pascalDomain %>sService _<%= domain %>sService;
        private readonly ILogger<Create<%= pascalDomain %>> _logger;
        #endregion

        #region constructors
        public <%= pascalDomain %>sController(
            IBusPublisher busPublisher, 
            ITracer tracer,
            I<%= pascalDomain %>sService <%= domain %>sService,ILogger<Create<%= pascalDomain %>>logger) : base(busPublisher, tracer)
        {
            _<%= domain %>sService = <%= domain %>sService;
            _logger = logger;
        }
        #endregion

        #region public functions
         /// <summary>
        ///  Make a get query 
        /// </summary>
        /// <param name="query">The Query</param>
        /// <returns>A list of result</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Get([FromQuery] Browse<%= pascalDomain %>s query)
            => Collection(await _<%= domain %>sService.BrowseAsync(query));

        /// <summary>
        /// Search an Unique <%= domain %> based on its id
        /// </summary>
        /// <param name="id">The Id to search</param>
        /// <returns>The <%= domain %></returns>
        [HttpGet("{id}")]
        [AllowAnonymous]
        public async Task<IActionResult> Get(Guid id)
            => Single(await _<%= domain %>sService.GetAsync(id));

        /// <summary>
        ///  Create a new <%= domain %>
        /// </summary>
        /// <param name="command">The Create Command</param>
        /// <returns>Accepted response: The the operation Service</returns>
        [HttpPost]
        public async Task<IActionResult> Post(Create<%= pascalDomain %> command)
            => await SendAsync(command.BindId(c => c.Id,_logger),  resourceId: command.Id, resource: "<%= domain %>s");

        /// <summary>
        /// Update a <%= domain %>
        /// </summary>
        /// <param name="id">the id of <%= domain %> to update</param>
        /// <param name="command">The Update Command</param>
        /// <returns>Accepted response: The the operation Service</returns>
        [HttpPut("{id}")]
        public async Task<IActionResult> Put(Guid id, Update<%= pascalDomain %> command)
            => await SendAsync(command.Bind(c => c.Id, id),resourceId: command.Id, resource: "<%= domain %>s");

        /// <summary>
        /// Delete a <%= domain %>
        /// </summary>
        /// <param name="id">the id of <%= domain %> to delete</param>
        /// <returns>Accepted response: The the operation Service</returns>
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
            => await SendAsync(new Delete<%= pascalDomain %>(id));

        #endregion
    }
}
