
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Domain;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Dto;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.Services.Repositories
{    

    #region interface
    /// <summary>
    /// <%= changeCase.pascalCase(name) %> Repository for intereaction with database
    /// </summary>
    public interface IBrowse<%= changeCase.pascalCase(name) %>Repository : IBrowseRepository<<%= changeCase.pascalCase(name) %>,Browse<%= changeCase.pascalCase(name) %>s,<%= changeCase.pascalCase(name) %>Dto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// <%= changeCase.pascalCase(name) %> Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowse<%= changeCase.pascalCase(name) %>Repository))]
    public partial class <%= changeCase.pascalCase(name) %>Repository : BrowseRepository<<%= changeCase.pascalCase(name) %>,Browse<%= changeCase.pascalCase(name) %>s,<%= changeCase.pascalCase(name) %>Dto>,IBrowse<%= changeCase.pascalCase(name) %>Repository 
    {
        public <%= changeCase.pascalCase(name) %>Repository(IMongoRepository<<%= changeCase.pascalCase(name) %>> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}