
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using <%=appname%>.domain.<%= domain %>s.Domain;
using <%=appname%>.domain.<%= domain %>s.Dto;
using <%=appname%>.domain.<%= domain %>s.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=service.name%>.Repositories
{    

    #region interface
    /// <summary>
    /// <%= pascalDomain %> Repository for intereaction with database
    /// </summary>
    public interface IBrowse<%= pascalDomain %>Repository : IBrowseRepository<<%= pascalDomain %>,Browse<%= pascalDomain %>s,<%= pascalDomain %>Dto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// <%= pascalDomain %> Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowse<%= pascalDomain %>Repository))]
    public partial class <%= pascalDomain %>Repository : BrowseRepository<<%= pascalDomain %>,Browse<%= pascalDomain %>s,<%= pascalDomain %>Dto>,IBrowse<%= pascalDomain %>Repository 
    {
        public <%= pascalDomain %>Repository(IMongoRepository<<%= pascalDomain %>> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}