using AutoMapper;
using <%=appname%>.domain.<%= domain%>s.Domain;
using <%=appname%>.domain.<%= domain%>s.Dto;
<%if(crud){%>
using <%=appname%>.domain.<%= domain%>s.Messages.Commands;
using <%=appname%>.domain.<%= domain%>s.Messages.Events;
<%}%>
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.domain.<%= domain%>s.Mapping
{
    public class <%= pascalDomain%>Profile:Profile
    {
        public <%= pascalDomain%>Profile()
        {
            CreateMap<<%= pascalDomain%>, <%= pascalDomain%>Dto>();
            <%if(crud){%>
            CreateMap<Create<%= pascalDomain%>, <%= pascalDomain%>>();
            CreateMap<Create<%= pascalDomain%>, <%= pascalDomain%>Created>();
            CreateMap<Update<%= pascalDomain%>, <%= pascalDomain%>Updated>();
            CreateMap<Delete<%= pascalDomain%>, <%= pascalDomain%>Deleted>();
            <%}%>
        }
    }
}
