using AutoMapper;
using MicroS_Common.Handlers;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Domain;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Dto;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Queries;
using <%=namespace%>.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.Services.Cotation.Handlers
{
    /// <summary>
    /// Browse <%= changeCase.pascalCase(name) %> Handler
    /// </summary>
    public partial class Browse<%= changeCase.pascalCase(name) %>HandlerGen : BaseBrowseHandler<<%= changeCase.pascalCase(name) %>, Browse<%= changeCase.pascalCase(name) %>s, <%= changeCase.pascalCase(name) %>Dto, IBrowse<%= changeCase.pascalCase(name) %>Repository>
    {
        public Browse<%= changeCase.pascalCase(name) %>HandlerGen(IBrowse<%= changeCase.pascalCase(name) %>Repository repository, IMapper mapper) : base(repository, mapper){}
    }
}
