using AutoMapper;
using Microsoft.Extensions.Logging;
using MicroS_Common.Handlers;
using <%=appname%>.domain.<%= domain %>s.Domain;
using <%=appname%>.domain.<%= domain %>s.Dto;
using <%=appname%>.domain.<%= domain %>s.Queries;
using <%=service.name%>.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=service.name%>.Handlers
{
    /// <summary>
    /// Browse <%= pascalDomain %> Handler
    /// </summary>
    public partial class Browse<%= pascalDomain %>Handler : BaseBrowseHandler<<%= pascalDomain %>, Browse<%= pascalDomain %>s, <%= pascalDomain %>Dto, IBrowse<%= pascalDomain %>Repository>
    {
        public Browse<%= pascalDomain %>Handler(IBrowse<%= pascalDomain %>Repository repository, IMapper mapper,ILogger<Browse<%= pascalDomain %>Handler> logger): base(repository, mapper,logger){}
    }
}
