using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.RabbitMq;
using MicroS_Common.Types;
using MicroS_Common.Mongo;
using System.Threading.Tasks;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Domain;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Messages.Commands;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name) %>s.Messages.Events;
using <%=namespace%>.Services.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.Services.<%= changeCase.pascalCase(name) %>s.Handlers
{


    /// <summary>
    /// Delete <%= changeCase.pascalCase(name) %> Handler
    /// </summary>
    public partial class Delete<%= changeCase.pascalCase(name) %>Handler : DomainCommandHandler<Delete<%= changeCase.pascalCase(name) %>, <%= changeCase.pascalCase(name) %>>
    {
        #region Constructors
        public Delete<%= changeCase.pascalCase(name) %>Handler(
            IBusPublisher busPublisher, 
            IMapper mapper, 
            IBrowse<%= changeCase.pascalCase(name) %>Repository repository) : base(busPublisher, mapper, repository)
        {
        }
        #endregion
        #region Protected Overrides functions
        /// <summary>
        /// Check if the model exist by Command
        /// </summary>
        /// <param name="command">The command in wich information can be use do check if the model exist in database</param>
        /// <returns>Nothing</returns>
        protected override async Task CheckExist(<%= changeCase.pascalCase(name) %> domain)
        {
            if (!await Repository.ExistsAsync(domain.Id))
            {
                throw new MicroSException("<%= changeCase.lowerCase(name) %>_not_found",$"<%= changeCase.pascalCase(name) %>: '{domain.Id}'  was not found.");
            }

        }
        #endregion

        #region Public Overrides functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public override async Task HandleAsync(Delete<%= changeCase.pascalCase(name) %> command, ICorrelationContext context)
        {
            await base.HandleAsync(command, context);
            await Repository.DeleteAsync(command.Id);
            await BusPublisher.PublishAsync(CreateEvent<<%= changeCase.pascalCase(name) %>Deleted>(command) , context);

        }
        #endregion
    }
}
