using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.Mongo;
using System.Threading.Tasks;
using <%=appname%>.domain.<%= domain %>s.Dto;
using <%=appname%>.domain.<%= domain %>s.Queries;
using <%=service.name%>.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=service.name%>.Handlers
{
    /// <summary>
    /// Get <%= pascalDomain %> Handler
    /// </summary>
    public partial class Get<%= pascalDomain %>Handler :  IQueryHandler<Get<%= pascalDomain %>, <%= pascalDomain %>Dto>
    {
        

        #region Constructors
        public Get<%= pascalDomain %>Handler(
            IBrowse<%= pascalDomain %>Repository repository,
             IMapper mapper)
        {
            Repository = repository;
            Mapper = mapper;
        }
        #endregion

        #region public properties
        public IBrowse<%= pascalDomain %>Repository Repository{get;}
        public IMapper Mapper{get;}
        #endregion

        #region public functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public async Task<<%= pascalDomain %>Dto> HandleAsync(Get<%= pascalDomain %> query)
        {
            var model = await Repository.GetAsync(query.Id);

            return model == null ? null : Mapper.Map<<%= pascalDomain %>Dto>(model);

        }
        #endregion
    }
}