using MicroS_Common.Types;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Queries
{
    public class Browse<%= changeCase.pascalCase(name)%>s : PagedQueryBase, IQuery<PagedResult<<%= changeCase.pascalCase(name)%>Dto>>
    {
    }
}
