using MicroS_Common.Types;
using System;
using <%=appname%>.domain.<%= domain%>s.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.domain.<%= domain%>s.Queries
{
    public class Get<%= pascalDomain%> : IQuery<<%= pascalDomain%>Dto>
    {
        #region public properties
        <%if(entity){%>
            public Guid Id { get; set; }
        <% } %>
        #endregion
        
    }
}
