using MicroS_Common.Types;
using System;
using <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Queries
{
    public class Get<%= changeCase.pascalCase(name)%> : IQuery<<%= changeCase.pascalCase(name)%>Dto>
    {
        #region public properties
        <%if(base_entity){%>
            public Guid Id { get; set; }
        <% } %>
        #endregion
        
    }
}
