version: '3.5'
 
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
   container_name: elasticsearch
   ports:
   - 9200:9200
   
   environment:
     - "discovery.type=single-node"
   networks:
     - net
   volumes:
     - esdata:/usr/share/elasticsearch/data
 
 kibana:
   image: docker.elastic.co/kibana/kibana:7.6.2
   container_name: kibana
   ports:
   - 5601:5601
   environment:
     SERVER_NAME : kibana
     ELASTICSEARCH_URL : http://elasticsearch:9200
   networks:
     - net
 
 proxy:
   build : ./nginx
   container_name : proxy
   ports:
     - "8080:80"
   networks:
     - net
 
volumes:
   esdata:
     driver: local
 
networks:
   net: