version: "3.5"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - micros
    # network_mode: host
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=smtp.free.fr:25"
      - "GF_SMTP_USER=jc.ambert@free.fr"
      - "GF_SMTP_PASSWORD=nf869362"
      - "GF_SMTP_FROM_ADDRESS=jc.ambert.weping@free.fr"
      - "GF_FROM_NAME=WePing Monitoring"

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    networks:
      - micros
    # network_mode: host
    volumes:
      - influxdb:/var/lib/influxdb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - micros
    # network_mode: host
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  micros:
    name: micros-network
    external: true

volumes:
  grafana:
    driver: local

  influxdb:
    driver: local
  prometheus:
    driver: local