version: "3.5"

services:
  jasper-server:
    build:
      context: ../docker/jasper
    container_name: jasper-server
    ports:
      - 8443:8080
    networks:
      - micros
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:latest
    container_name: postgres-client
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/db/postgres
  
networks:
  micros:
    name: micros-network
    external: true

volumes:
  postgres:
    driver: local
