version: "3.5"

services:
  vscode:
    image: codercom/code-server:v2
    container_name: code-server
    ports:
      - 8080:8080
    environment:
      PASSWORD: korben90
    volumes:
      - "D:/projets/MicroServices:/home/coder/.local/share/code-server"
    networks:
      - micros
  

networks:
  micros:
    name: micros-network
    external: true