using System;
using MicroS_Common.Messages;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=appname%>.domain.<%=domain %>s.Messages.Commands
{
    [MessageNamespace("<%=domain %>s")]
    public abstract class <%= pascalDomain %>BaseCommand : BaseCommand
    {

        public <%= pascalDomain %>BaseCommand() : base()
        {
        }
    }
}
