using System;
using MicroS_Common.Messages;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%=changeCase.pascalCase(name) %>s.Messages.Commands
{
    [MessageNamespace("<%=changeCase.lowerCase(name) %>s")]
    public abstract class <%=changeCase.pascalCase(name) %>BaseCommand : BaseCommand
    {

        public <%=changeCase.pascalCase(name) %>BaseCommand() : base()
        {
        }
    }
}
