using System;
<%- include('./../../../common/templates/using') %>
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Messages.Commands
{

    public class Create<%= changeCase.pascalCase(name)%> : <%= changeCase.pascalCase(name)%>BaseCommand
    {
        <%if(base_entity){%>
        public override Guid Id { get; set; }
        <%}%>
        <%-props.filter(prop=>prop.isprimitive).map(prop=>`public ${prop.type} ${changeCase.pascalCase(prop.name)} {get;}`).join('\n') %>
        <%-props.filter(prop=>!prop.isprimitive).map(prop=>`public List<${changeCase.pascalCase(prop.name)}> ${changeCase.pascalCase(prop.name)}s {get;}`).join('\n') %>



        public Create<%= changeCase.pascalCase(name)%>(
            <%if(base_entity){%>Guid id,<%}%><%- include('./../../../common/templates/ctor') %>) : base()
        {
            <%if(base_entity){%>
            Id = id;
            <%}%>
            <%- include('./../../../common/templates/ctorsetprops') %>
           
        }
    }
}
