using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Messages.Commands
{
    public class Delete<%= changeCase.pascalCase(name)%>: <%= changeCase.pascalCase(name)%>BaseCommand
    {
        <%if(base_entity){%>
        public override Guid Id { get; set; }
        public Delete<%= changeCase.pascalCase(name)%>(Guid id) : base()
        {
            this.Id = id;
        }
        <%}else{%>
         public Delete<%= changeCase.pascalCase(name)%>() : base(){
             //TODO SET AN ID HERE
         }
        <%}%>

    }
}