using System;
<%- include('./../../../common/templates/using') %>
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%=namespace%>.domain.<%= changeCase.pascalCase(name)%>s.Messages.Commands
{
    public class Update<%= changeCase.pascalCase(name)%> : Create<%= changeCase.pascalCase(name)%>
    {
        
        public Update<%= changeCase.pascalCase(name)%>(<%if(base_entity){%>Guid id,<%}%><%- include('./../../../common/templates/ctor') %>) : base(<%if(base_entity){%>id,<%}%><%- include('./../../../common/templates/ctorbase') %>)
        {
        }
    }
}
