#region using
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using MicroS_Common;
using MicroS_Common.Types;
using MicroS_Common.Controllers;
using MicroS_Common.Dispatchers;
using <%=appname%>.domain.<%= domain %>s.Dto;
using <%=appname%>.domain.<%= domain %>s.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: <%=author.name%>
/// @email: <%=author.email%>
/// @created_on: <%= new Date()%>
/// </summary>
namespace <%= service.name %>.Controllers
{
    [Route("<%= domain %>s")]
    public partial class <%= pascalDomain %>sController : BaseController
    {
        public <%= pascalDomain %>sController(IDispatcher dispatcher,IConfiguration config,IOptions<AppOptions> appOptions) : base(dispatcher,config,appOptions)
        {
        }

        [HttpGet("")]
        public async Task<ActionResult<PagedResult<<%= pascalDomain %>Dto>>> Get([FromQuery] Browse<%= pascalDomain %>s query)
            => Collection(await QueryAsync(query));

        [HttpGet("{id}")]
        public async Task<ActionResult<<%= pascalDomain %>Dto>> Get([FromRoute] Get<%= pascalDomain %> query)
            => Single(await QueryAsync(query));
        
        
    }
}